### ISSUE TITLE
Expand the config file to support different options for different gateways

### ISSUE THREAD

**Issue by bachya** [bachya/ecowitt2mqtt#196]
A recent test revealed that when using Home Assistant MQTT Discovery, `ecowitt2mqtt` [can support multiple gateways](https://community.home-assistant.io/t/ecowitt2mqtt-send-data-from-an-ecowitt-device-to-mqtt/231169/84?u=bachya). This is excellent news, as I didn't explicitly architect it to do so. 😂 

However, it made me realize that the experience for the "basic" MQTT publisher (i.e., the default one) isn't as clean or easy (as I'll share shortly). Users should have the same capability whether they're using Home Assistant. So, this topic is to track thoughts/discussions around the best way to implement.

## Idea 1: Spin up a separate instance of `ecowitt2mqtt`.

In this scenario, the user would be instructed to use one instance of `ecowitt2mqtt` for each gateway. Incidentally, if someone asked how to accomplish multiple gateways today, they would be given this answer.

**Pros:**

* Already supported

**Cons:**

* Wasteful (new Docker container/systemd unit/etc. for each service)
* Philosophically strange – why would it be this way by default, but Home Assistant MQTT Discovery would get a more straightforward route?

## Idea 2: Add an option to automatically prefixt the MQTT topic with a unique ID.

In this scenario, the user would provide a new boolean option (e.g., `--mqtt-topic-unique-id`), and `ecowitt2mqtt` would, under the hood, prepend the value of `--mqtt-topic` with each gateway's unique ID. For example, if the user provides an `--mqtt-topic` of `Test`, the final topic would be `<UNIQUE_ID>/Test`.

**Pros:**

* Relatively easy to implement
* Can be ignored by users who only have one gateway (would be `false` by default to maintain backward compatibility)

**Cons:**

* It muddles up the (admittedly already-difficult) CLI interface – how would the user know this option applies only to this basic publisher type?
* A little too automagical for my taste...

## Idea 3: Expand the configuration file to include proper gateway configurations.

In this scenario, the config file would be expanded so that individual gateways could have their own options:

```yaml
gateways:
  gateway_123:
    mqtt_topic: gateway_123/Test
  gateway_456:
    mqtt_topic: gateway_456/Test
```

This would even allow for all sorts of new scenarios (like sending gateways to different MQTT brokers, using different log verbosity levels depending on the gateway, etc.).

**Pros:**

* Very declarative
* Straightforward hierarchy
* Opens up new possibilities (like multiple MQTT brokers that would be difficult today without resorting to Idea 1)

**Cons:**

* The config file goes from a nice-to-have to having more of a center stage (is that a bad thing?)
* More work to take existing CLI options/env vars and translate them into a comparable hierarchy
* Is this going too far the other way (i.e., instead of being automagical, we're being _too_ explicit)?

**Comment by Anto79-ops** [comment]
I may not know all the technical implications of all the options but option 3 does sound more appealing.

In the case of the basic mqtt output the topic line would have to be different for each Gateway as you've Illustrated in the sample code

**Comment by bachya** [comment]
> In the case of the basic mqtt output the topic line would have to be different for each Gateway as you've Illustrated in the sample code

That's correct, which brings up a good snag to be aware of: we would need to ensure the unique-ness of each topic the user provides.

**Comment by bachya** [comment]
Let's explore 3 a bit more.

Today, the config file allows for the same options as provided by the CLI and env vars. For example, a "complete" YAML config file might look like this:

```yaml
---
battery_override:
  battery_key1: boolean
default_battery_strategy: numeric,
diagnostics: false
endpoint: /data/report,
hass_discovery: false,
hass_discovery_prefix: homeassistant,
hass_entity_id_prefix: test_prefix
input_unit_system: imperial,
mqtt_broker: 127.0.0.1,
mqtt_password: password,
mqtt_port: 1883,
mqtt_tls: false,
mqtt_topic: Test,
mqtt_username: user,
output_unit_system: imperial,
port: 8080,
raw_data: false,
verbose: false
```

It's worth looking at each field and digging into how it looks in a multi-config world:

Option | Thoughts |
-------|-----------|
`battery_override` | Each gateway could have its own set |
`default_battery_strategy` | Each gateway could have its own |
`diagnostics` | This doesn't make sense on a per-gateway basis as-is today... |
`endpoint` | This is only needed once (e.g., there's no reason each gateway needs to hit a different `ecowitt2mqtt` endpoint |
`hass_discovery` | We could have each gateway determine whether it should publish in `hass_discovery` mode or not... |
`hass_discovery_prefix` | Same as above |
`hass_entity_id_prefix` | Same as above |
`input_unit_system` | Each gateway could have its own |
`mqtt_broker` | Each gateway could have its own |
`mqtt_password` | Each gateway could have its own |
`mqtt_port` | Each gateway could have its own |
`mqtt_tls` | Each gateway could have its own |
`mqtt_topic` | Each gateway could have its own |
`mqtt_username` | Each gateway could have its own |
`output_unit_system` | Each gateway could have its own |
`port` | This is only needed once (e.g., there's no reason each gateway needs to hit a different `ecowitt2mqtt` port |
`raw_data` | Each gateway could have its own setting |
`verbose` | Each gateway could have its own setting |

From this, I see some interesting points:

* Some options only make sense when defined once (across all possible gateways)
* For many options, it makes sense to have the possibility for unique values per gateway.
* In many cases, options can be defined as defaults and then overridden by specific configs.
* Whether as a default or as a per-gateway option, some options – like `hass_discovery` – invalidate the presence of other options (again, per gateway).
* We would need to receive data to set many options (because we'll need to know which gateway the data is arriving from) – this is different from how it is today, where configuration is set before any data is received.

---

Let's look at a couple of config possibilities (taking all of these points into account). To start, we could imagine a config file that defines (a) a default MQTT broker used by all gateways and (b) a unique MQTT topic per gateway:

```yaml
---
default:
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_username: user

gateways:
  gateway_id_1:
    mqtt_topic: gateway_id_1

  gateway_id_2:
    mqtt_topic: gateway_id_2
```

We could imagine one gateway publishing raw data in basic mode and another publishing in HASS MQTT Discovery mode with verbose logging:

```yaml
---
default:
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_username: user

gateways:
  gateway_id_1:
    mqtt_topic: gateway_id_1
    raw_data: true

  gateway_id_2:
    hass_discovery: true
    verbose: true
```

We could imagine a user trying to override options that make sense only when the same across gateways and `ecowitt2mqtt` just ignoring that:

```yaml
---
default:
  endpoint: /data/report
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_username: user

gateways:
  gateway_id_1:
    mqtt_topic: gateway_id_1
    raw_data: true

  gateway_id_2:
    endpoint: /foo/bar
    # We would ignore ^ (and perhaps log a warning)
```

It is technically allowable to list defaults and a single gateway:

```yaml
---
default:
  endpoint: /data/report
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_username: user

gateways:
  gateway_id_1:
    mqtt_topic: gateway_id_1
```

...which would be the same as:

```yaml
---
default:
  endpoint: /data/report
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_topic: gateway_id_1
  mqtt_username: user
```

...which would be the same as:

```yaml
---
default:
  endpoint: /data/report
  mqtt_broker: 127.0.0.1
  mqtt_password: password
  mqtt_port: 1883
  mqtt_username: user

gateways:
  gateway_id_1:
      endpoint: /data/report
      mqtt_broker: 127.0.0.1
      mqtt_password: password
      mqtt_port: 1883
      mqtt_topic: gateway_id_1
      mqtt_username: user
```

(Maybe we warn the user that this can be consolidated, or maybe we don't care.)
