### ISSUE TITLE
ecowitt2mqtt partially ignores configuration file

### ISSUE THREAD

**Issue by stefa168** [bachya/ecowitt2mqtt#287]
Hi, I am currently migrating from your HA addon to directly using Docker for ecowitt2mqtt. I'm having some issues regarding the configuration file, as it looks like e2m is partially ignoring my configuration.

Right now my docker-compose file looks like this:

```
version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto/
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9002:9002
    restart: unless-stopped

  ecowitt2mqtt:
    container_name: ecowitt2mqtt
    image: bachya/ecowitt2mqtt:latest
    volumes:
      - ./ecowitt2mqtt:/config
    environment:
      ECOWITT2MQTT_CONFIG: /config/config.yaml
      ECOWITT2MQTT_VERBOSE: true
    ports:
      - 8125:8080
    restart: unless-stopped
    depends_on:
      - mosquitto
```
I've set the `ECOWITT2MQTT_VERBOSE` environment variable to true to get some logs when running.

Right now e2m manages to connect to mosquitto and can publish messages (I checked with MQTT Explorer), however it ignores part of my settings file, which looks like this:

```yml
battery_override:
  battery_key1: boolean
default_battery_strategy: numeric
diagnostics: false
disable_calculated_data: false
endpoint: /data/report
hass_discovery: true
hass_discovery_prefix: homeassistant
hass_entity_id_prefix: WH2650A
input_unit_system: imperial
output_unit_system: metric
mqtt_broker: mosquitto
mqtt_username: e2m
mqtt_password: '123456789'
mqtt_port: 1883
mqtt_retain: false
mqtt_tls: false
mqtt_topic: weather
port: 8125
raw_data: false
verbose: true
```

As I said, it looks like it is ignoring partially my configuration as it doesn't set the verbosity to true without an environment variable, the port it is listening to is wrong (8080 as the following log says, instead of 8125, which I had to map manually within the compose file to receive some data from my station) and the temperatures published are not in Celsius but Fahrenheit. 
Also, it managed to connect to my mosquitto instance, which requires a username and password. It publishes to HA and 

```json
{
	"runtime": 1394925,
	"tempin": 78.1,
	"humidityin": 66,
	"baromrel": 29.06,
	"baromabs": 29.06,
	"temp": 69.3,
	...
}
```

```log
ecowitt2mqtt  | 2022-09-07 21:00:45,917 | ecowitt2mqtt | DEBUG | CLI options: {'battery_override': (), 'config': '/config/config.yaml', 'default_battery_strategy': 'boolean', 'diagnostics': False, 'disable_calculated_data': False, 'endpoint': '/data/report', 'hass_discovery': False, 'hass_discovery_prefix': 'homeassistant', 'hass_entity_id_prefix': None, 'input_unit_system': 'imperial', 'mqtt_broker': None, 'mqtt_password': None, 'mqtt_port': 1883, 'mqtt_retain': False, 'mqtt_tls': False, 'mqtt_topic': None, 'mqtt_username': None, 'output_unit_system': 'imperial', 'port': 8080, 'raw_data': False, 'verbose': True, 'version': False}
ecowitt2mqtt  | 2022-09-07 21:00:45,918 | ecowitt2mqtt | DEBUG | Loaded Config: {'battery_override': {}, 'default_battery_strategy': 'boolean', 'diagnostics': False, 'disable_calculated_data': False, 'endpoint': '/data/report', 'hass_discovery': False, 'hass_discovery_prefix': 'homeassistant', 'hass_entity_id_prefix': 'WH2650A', 'input_unit_system': 'imperial', 'output_unit_system': 'imperial', 'mqtt_broker': 'mosquitto', 'mqtt_username': 'e2m', 'mqtt_password': '123456789', 'mqtt_port': 1883, 'mqtt_retain': False, 'mqtt_tls': False, 'mqtt_topic': 'weather', 'port': 8080, 'raw_data': False, 'verbose': True, 'config': '/config/config.yaml', 'version': False}
ecowitt2mqtt  | 2022-09-07 21:00:45,919 | ecowitt2mqtt | INFO | Starting ecowitt2mqtt (version 2022.08.3)
ecowitt2mqtt  | 2022-09-07 21:00:45,920 | ecowitt2mqtt | DEBUG | Starting MQTT process loop
ecowitt2mqtt  | 2022-09-07 21:00:45,920 | ecowitt2mqtt | DEBUG | Starting REST API server
ecowitt2mqtt  | 2022-09-07 21:00:45,924 | ecowitt2mqtt | DEBUG | Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
ecowitt2mqtt  | 2022-09-07 21:00:45,924 | uvicorn.error | INFO | Started server process [7]
ecowitt2mqtt  | 2022-09-07 21:00:45,924 | uvicorn.error | INFO | Waiting for application startup.
ecowitt2mqtt  | 2022-09-07 21:00:45,925 | ecowitt2mqtt | DEBUG | Received CONNACK (0, 0)
ecowitt2mqtt  | 2022-09-07 21:00:45,925 | uvicorn.error | INFO | Application startup complete.
ecowitt2mqtt  | 2022-09-07 21:00:45,925 | uvicorn.error | INFO | Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

There must be something that I'm doing wrong; could you give some hints? I've spent a lot of time looking at this issue, but I'm not able to find the cause...
Thanks!
