### ISSUE TITLE
Raspberry Pi 4, docker: ImportError: Error loading shared library ld-linux-armhf.so.3

### ISSUE THREAD

**Issue by strombringer** [bachya/ecowitt2mqtt#442]
**Describe the bug**
I'm trying to run ecowitt2mqtt as a docker container on my Raspberry Pi 4 but it fails with the log message below.
The same docker-compose file works fine on my Windows machine.

Does the log mean anything to you?

**To Reproduce**

1. Use the following docker-compose.yml (mosquitto config omitted for brevity):
```
services:
  mosquitto:
    ...

  ecowitt2mqtt:
    container_name: ecowitt2mqtt
    image: bachya/ecowitt2mqtt:latest
    environment:
    - ECOWITT2MQTT_MQTT_BROKER=mosquitto
    - ECOWITT2MQTT_MQTT_PASSWORD=***
    - ECOWITT2MQTT_MQTT_USERNAME=weather
    - ECOWITT2MQTT_MQTT_TOPIC=weather-ws3500
    - ECOWITT2MQTT_MQTT_RETAIN=true
    - ECOWITT2MQTT_VERBOSE=true
    - ECOWITT2MQTT_DIAGNOSTICS=true
    - ECOWITT2MQTT_HASS_DISCOVERY=false
    - ECOWITT2MQTT_INPUT_UNIT_SYSTEM=metric
    - ECOWITT2MQTT_OUTPUT_UNIT_SYSTEM=metric
    ports:
      - "13002:8080/tcp"
    restart: unless-stopped
    depends_on:
    - mosquitto
```
2. `$ docker-compose up -d`

**Expected behavior**
The container should start without errors.

**Additional context**

image id: sha256:a99496c39a5dfeb092b02be3449e8a56806c31156945125a92ec072af35f3811

container log:
```
s6-rc: info: service ecowitt2mqtt: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service ecowitt2mqtt successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/venv/bin/ecowitt2mqtt", line 5, in <module>
    from ecowitt2mqtt.__main__ import main
  File "/venv/lib/python3.9/site-packages/ecowitt2mqtt/__main__.py", line 10, in <module>
    import uvloop
  File "/venv/lib/python3.9/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /venv/lib/python3.9/site-packages/uvloop/loop.cpython-39-arm-linux-gnueabihf.so)
Traceback (most recent call last):
  File "/venv/bin/ecowitt2mqtt", line 5, in <module>
    from ecowitt2mqtt.__main__ import main
  File "/venv/lib/python3.9/site-packages/ecowitt2mqtt/__main__.py", line 10, in <module>
    import uvloop
  File "/venv/lib/python3.9/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /venv/lib/python3.9/site-packages/uvloop/loop.cpython-39-arm-linux-gnueabihf.so)
...
```

**Comment by bachya** [comment]
Looks like `uvloop` isn't installing correctly on ARM processes. Did this docker image work on the Pi 4 previously, or is this the first time you're trying it?

**Comment by strombringer** [comment]
It's the first time I'm trying it

**Comment by bachya** [comment]
Can you SSH into your Pi and run the following shell command and paste the response?

```sh
docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" bachya/ecowitt2mqtt:latest
```

**Comment by strombringer** [comment]
```
sha256:a99496c39a5dfeb092b02be3449e8a56806c31156945125a92ec072af35f3811 [bachya/ecowitt2mqtt:latest] arm
```

**Comment by bachya** [comment]
Thank you. Looks like you're running a 32-bit architecture (`armhf`) on your Pi. I only have a 64-bit architecture (`aarch64/arm64`) to test on, unfortunately:

```sh
docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" bachya/ecowitt2mqtt:latest
# >>> sha256:25f8558f25f7cba3b4295fde3372fb511b7a59fd9f5aa35db0495272d25d2203 [bachya/ecowitt2mqtt:latest] arm64
```

This images works as expected with this configuration:

```yaml
---
version: "3"

services:
  ecowitt2mqtt:
    container_name: ecowitt2mqtt
    environment:
      ECOWITT2MQTT_MQTT_BROKER: pmc-vm-homeassistant.phil.servers
      ECOWITT2MQTT_MQTT_PASSWORD: "Iatvpok0##07"
      ECOWITT2MQTT_MQTT_TOPIC: ecowitt2mqtt_test
      ECOWITT2MQTT_MQTT_USERNAME: ecowitt2mqtt_test
      ECOWITT2MQTT_VERBOSE: "true"
    image: bachya/ecowitt2mqtt:latest
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped
```

```
[+] Running 1/0
 ⠿ Container ecowitt2mqtt  Created                                                                               0.0s
Attaching to ecowitt2mqtt
ecowitt2mqtt  | s6-rc: info: service ecowitt2mqtt: starting
ecowitt2mqtt  | s6-rc: info: service s6rc-oneshot-runner: starting
ecowitt2mqtt  | s6-rc: info: service ecowitt2mqtt successfully started
ecowitt2mqtt  | s6-rc: info: service s6rc-oneshot-runner successfully started
ecowitt2mqtt  | s6-rc: info: service fix-attrs: starting
ecowitt2mqtt  | s6-rc: info: service fix-attrs successfully started
ecowitt2mqtt  | s6-rc: info: service legacy-cont-init: starting
ecowitt2mqtt  | s6-rc: info: service legacy-cont-init successfully started
ecowitt2mqtt  | s6-rc: info: service legacy-services: starting
ecowitt2mqtt  | s6-rc: info: service legacy-services successfully started
ecowitt2mqtt  | 2023-02-08 19:20:38,690 | DEBUG | Input CLI options/environment variables: {'mqtt_broker': 'pmc-vm-homeassistant.phil.servers', 'mqtt_password': 'Iatvpok0##07', 'mqtt_topic': 'ecowitt2mqtt_test', 'mqtt_username': 'ecowitt2mqtt_test', 'verbose': 'true'}
ecowitt2mqtt  | 2023-02-08 19:20:38,690 | DEBUG | Configs loaded: <Configs _configs={'default': {'mqtt_broker': 'pmc-vm-homeassistant.phil.servers', 'mqtt_password': 'Iatvpok0##07', 'mqtt_topic': 'ecowitt2mqtt_test', 'mqtt_username': 'ecowitt2mqtt_test', 'verbose': True, 'hass_discovery': False, 'disable_calculated_data': False, 'raw_data': False, 'battery_override': {}, 'port': 8080, 'input_data_format': <InputDataFormat.ECOWITT: 'ecowitt'>, 'mqtt_retain': False, 'default_battery_strategy': <BatteryStrategy.BOOLEAN: 'boolean'>, 'mqtt_tls': False, 'output_unit_system': 'imperial', 'diagnostics': False, 'input_unit_system': 'imperial', 'endpoint': '/data/report', 'mqtt_port': 1883}}
ecowitt2mqtt  | 2023-02-08 19:20:38,691 | INFO | Starting ecowitt2mqtt (version 2023.01.0)
ecowitt2mqtt  | 2023-02-08 19:20:38,691 | DEBUG | Starting runtime
ecowitt2mqtt  | INFO:     Started server process [44]
ecowitt2mqtt  | INFO:     Waiting for application startup.
ecowitt2mqtt  | INFO:     Application startup complete.
ecowitt2mqtt  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

So, I think you have two options:

- Upgrade your Pi 4 to a 64-bit OS ([download](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit))
- Search for how to resolve issues with `ld-linux-armhf` on a 32-bit Raspberry Pi
