### ISSUE TITLE
Unable to start on Timberwolf Server since 2023.06.0

### ISSUE THREAD

**Issue by gr6803** [bachya/ecowitt2mqtt#661]
I run ecowitt2mqtt in a docker environment, managed by portainer. The image 2023.02.1 worked fine for months.
When trying to use the latest imgae (2023.07.0) the image didn't start anymore. The error message was 
"OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/init": stat /init: no such file or directory: unknown"
So i tried version by version starting at 2023.02.1. The latest working version was 2023.05.0.
Versions 2023.06.0 and later produce this error.
I think, "/init" referes to **Config\Entrypoint** .

<img width="432" alt="image" src="https://github.com/bachya/ecowitt2mqtt/assets/80448606/b16de1bc-0939-4b6c-bd19-152da029dd99">

**Comment by bachya** [comment]
I am not able to reproduce this. This `docker-compose.yml` (which references the latest `ecowitt2mqtt`):

```yaml
---
version: "3"

services:
  ecowitt2mqtt:
    environment:
      ECOWITT2MQTT_MQTT_BROKER: 127.0.0.1
      ECOWITT2MQTT_MQTT_PASSWORD: password
      ECOWITT2MQTT_MQTT_TOPIC: Test
      ECOWITT2MQTT_MQTT_USERNAME: ecowitt
      ECOWITT2MQTT_VERBOSE: "true"
    image: bachya/ecowitt2mqtt:2023.07.0
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped
```

...successfully launches the app and produces the expected log output:

```
ecowitt2mqtt-ecowitt2mqtt-1  | 2023-08-16 14:18:06,963 | DEBUG | Input CLI options/environment variables: {'mqtt_broker': '127.0.0.1', 'mqtt_password': 'password', 'mqtt_topic': 'Test', 'mqtt_username': 'ecowitt', 'verbose': 'true'}
ecowitt2mqtt-ecowitt2mqtt-1  | 2023-08-16 14:18:06,963 | DEBUG | Configs loaded: <Configs _configs={'default': {'mqtt_broker': '127.0.0.1', 'mqtt_password': 'password', 'mqtt_topic': 'Test', 'mqtt_username': 'ecowitt', 'verbose': True, 'input_unit_system': 'imperial', 'mqtt_retain': False, 'endpoint': '/data/report', 'disable_calculated_data': False, 'diagnostics': False, 'output_unit_system': 'imperial', 'mqtt_port': 1883, 'input_data_format': <InputDataFormat.ECOWITT: 'ecowitt'>, 'mqtt_tls': False, 'raw_data': False, 'port': 8080, 'battery_override': {}, 'default_battery_strategy': <BatteryStrategy.BOOLEAN: 'boolean'>}}
ecowitt2mqtt-ecowitt2mqtt-1  | 2023-08-16 14:18:06,964 | INFO | Starting ecowitt2mqtt (version 2023.07.0)
ecowitt2mqtt-ecowitt2mqtt-1  | 2023-08-16 14:18:06,964 | DEBUG | Starting runtime
ecowitt2mqtt-ecowitt2mqtt-1  | INFO:     Started server process [1]
ecowitt2mqtt-ecowitt2mqtt-1  | INFO:     Waiting for application startup.
ecowitt2mqtt-ecowitt2mqtt-1  | INFO:     Application startup complete.
ecowitt2mqtt-ecowitt2mqtt-1  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

What OS are you on? What are you using to launch the container?
