### ISSUE TITLE
Upgrading to 2023.11.0 Breaks Publishing

### ISSUE THREAD

**Issue by Silvenga** [bachya/ecowitt2mqtt#760]
**Describe the bug**
It appears that after upgrading from 2023.08.0 to 2023.11.0, MQTT publishing stopped working. Downgrading to 2023.08.0 restores previous behavior.

**To Reproduce**

```yaml
verbose: false
precision: 2
gateways:
  # GW2000B
  42B109437ED4E644FFF2DF549A1A0DAB:
    hass_entity_id_prefix: ecowitt_gw2000b
  # GW1100B
  55585D938764215B37D52CA7AD96E8F9:
    hass_entity_id_prefix: ecowitt_gw1100b
```

Environment variables:
```
  - name: ECOWITT2MQTT_MQTT_BROKER
    value: mqtt
  - name: ECOWITT2MQTT_MQTT_PORT
    value: "1883"
  - name: ECOWITT2MQTT_HASS_DISCOVERY
    value: "true"
  - name: ECOWITT2MQTT_PORT
    value: "8080"
  - name: ECOWITT2MQTT_CONFIG
    value: /config.yaml
```

**Expected behavior**

MQTT messages continue to publish.

**Additional context**

Logs similar to the following can be found:

```
[33m2023-11-05 16:50:28,652 | WARNING | There are 444 pending publish calls.[0m
```

[ecowitt2mqtt.log](https://github.com/bachya/ecowitt2mqtt/files/13261033/ecowitt2mqtt.log)
