### ISSUE TITLE
Precision doesn't work correctly when using `,` to delineate decimals

### ISSUE THREAD

**Issue by martinlindjarv** [bachya/ecowitt2mqtt#946]
**Describe the bug**
Docker image is runned with ECOWITT2MQTT_PRECISION: 3 but there are some parameters with lot of places after comma.
For example GW2000 dewpoint -> 4,294480528251863 °C

**To Reproduce**
Simply configure with default settings and enable ECOWITT2MQTT_PRECISION

**Expected behavior**
Expected is to have rounded value GW2000 dewpoint -> 4,29 °C

**Screenshots**
![image](https://github.com/bachya/ecowitt2mqtt/assets/29911525/82081733-0b73-4655-9860-02dc4e637657)

**Additional context**

**Comment by martinlindjarv** [comment]
As i wanted wind speed with m/s and not mph i needed to rewrite the CMD that is used to run ecowitt2mqtt inside container.

docker-compose.yaml:
```
  ecowitt2mqtt:
    image: bachya/ecowitt2mqtt:latest
    restart: unless-stopped
    container_name: ecowitt2mqtt
    command: "ecowitt2mqtt --output-unit-speed m/s --output-unit-humidity g/m³"
    environment:
      ECOWITT2MQTT_MQTT_BROKER: 192.168.1.1
      ECOWITT2MQTT_MQTT_PASSWORD: ***********
      ECOWITT2MQTT_MQTT_USERNAME: ecowitt
      ECOWITT2MQTT_MQTT_TOPIC: "weather"
      ECOWITT2MQTT_VERBOSE: false
      ECOWITT2MQTT_DIAGNOSTICS: false
      ECOWITT2MQTT_LOG_LEVEL: INFO
      ECOWITT2MQTT_HASS_DISCOVERY: true
      ECOWITT2MQTT_HASS_ENTITY_ID_PREFIX: "ecowitt"
      ECOWITT2MQTT_PRECISION: 3
    ports:
      - "8083:8080"
```
It all started to work ... precision is in place and all values rounded as i want ... 

Thanks for the great software!
