### ISSUE TITLE
HA Add-On cannot start when using external MQTT broker

### ISSUE THREAD

**Issue by valir** [bachya/ecowitt2mqtt#965]
**Describe the bug**
The Add-On refuses to start, ignores the `mqtt_host` or `mqtt_broker` configuration settings.

**To Reproduce**
Have an separate MQTT broker configured on the network
Go to the configuration file, choose "Edit in YAML" and use this config:

```YAML
boolean_battery_true_value: "1"
default_battery_strategy: numeric
diagnostics: false
disable_calculated_data: false
endpoint: /data/report
hass_discovery_prefix: homeassistant
input_data_format: ecowitt
input_unit_system: imperial
mqtt_retain: true
output_unit_system: imperial
precision: 1
verbose: true
hass_discovery: false
mqtt_host: 192.168.X.X
mqtt_broker: 192.168.X.X
```

**Expected behavior**
Add-on should connect to the external MQTT broker and successfully start

**Screenshots**

**Additional context**
I've tried to enter the setting `hass_discovery: false` in the YAML configuration, but it's being cleared upon save.

Log output:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ecowitt2mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[01:59:33] INFO: Fetching configuration...
[01:59:33] FATAL: MQTT configuration not found; cannot continue.
[22:59:34] WARNING: ecowitt2mqtt crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
