### ISSUE TITLE
Add 2 more "custom" sensors.

### ISSUE THREAD

**Issue by martinlindjarv** [bachya/ecowitt2mqtt#996]
Hi! 

Would it be possible to add 2 more sensors as calculated or any kind of customs sensors ?

Currently i'm using Wind Direction name and illuminance - both are HA templates:
```
  - platform: template
    sensors:
      ecowitt_wind_direction_name:
        friendly_name: "GW2000 Wind Direction Name"
        value_template: >
          {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
          {% set degree = states('sensor.ecowitt_winddir')|float(0) %}
          {{ direction[((degree+11.25)/22.5)|int] }}
```
and 
```
  - sensor:
      - name: "Illuminance"
        unit_of_measurement: "lx"
        device_class: illuminance
        state: "{{ states('sensor.ecowitt_solarradiation')|float * 126.7 }}"
```
Link where that _126.7_ came from -> https://ambientweather.com/faqs/question/view/id/1452/

If those would be added to ecowitt2mqtt it would be perfect!

If that would be the way to accomplish it trough HA - i'm thankful for this ecowitt2mqtt afterall!
But it is worth to ask :)

Martin
